### ISSUE TITLE
CRLF issue on Linux

### ISSUE THREAD

**Issue by cedricbompart** [alesveselka/concat-file-array#1]
Would you mind converting your **index.js** to a unix format please?  The file contains CRLF line terminators and it prevents to run the javascript file directly on a linux shell.

The directive **#!/usr/bin/env node** is not resolved because there are some dodgy CRLF characters.  I've created my own copy of your **index.js** and it works perfectly.

```
$ file node_modules/concat-file-array/src/js/index.js
node_modules/concat-file-array/src/js/index.js: Node.js script, ASCII text executable, with CRLF line terminators
```

**Comment by alesveselka** [comment]
It should be fixed now.

**Comment by cedricbompart** [comment]
Would you mind creating a new version please?  So it can be access through a NPM repository.
https://www.npmjs.com/package/concat-file-array
